# Generated by Django 2.2.2 on 2019-07-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your goal here', max_length=500)),
                ('description', models.TextField(help_text='Enter the decription of your goal here')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('daily_target', models.IntegerField(help_text='Enter a target number for your goal(i.e. 1,000 step per day')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('progress', models.IntegerField(help_text='Enter your progress here')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Goal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('owner', 'progress')},
            },
        ),
    ]
